selenium-hub:
  image: selenium/hub
  ports:
    - "4444:4444"

chrome:
  image: selenium/node-chrome
  links:
    - selenium-hub:hub
  environment:
    HUB_PORT_4444_TCP_ADDR: hub
    HUB_PORT_4444_TCP_PORT: 4444
  volumes:
    - /dev/shm:/dev/shm

# webapp:
#   image: crunch-diff/v1
#   links:
#     - selenium-hub:app
#   environment:
#     HUB_PORT_8080_TCP_ADDR: hub
#     HUB_PORT_8080_TCP_PORT: 8080
#   volumes:
#     - /dev/shm:/dev/shm
